project:
  type: website
  output-dir: docs

website:
  title: "My Thesis"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Methods
        href: methods.qmd
      - text: Results
        href: results.qmd
      - text: Discussion
        href: discussion.qmd

format:
  html:
    theme: cosmo
    toc: true

