project:
  type: website
  output-dir: docs

website:
  title: "My Thesis"
  sidebar:
    style: "docked"
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
          - amphi.qmd
          - parvus.qmd
      - section: "Methods"
        contents:
          - rawdata.qmd
      - section: "Discussion"
        contents:
          - discussion.qmd
      - section: "Miscellaneous"

format:
  html:
    theme: cosmo
    toc: true
